// 20 variables assignment//
let songName="song name";
let songTitle="song title";
let videogameName="Avengers";
let videogameNew="2022 game";
let userName="Johnny";
let songGenre="country";
let subscriptionGroup="My Group";
let usermailAddress="john.c.gray@gmail.com";
let accountId="My Id";
let shopbyAge="30";
let shopbyPrice="$20";
let ageRange="20-25";
let interestgenreToys="animals";
let popularBooks="popular";
let textbookTitle="title";
let bookFormat="book format";
let vehicleName="name of vehicle";
let autoPrice="price";
let petType="type of pet";
let sellerName="seller name";
document.writeln(`<p> ${songName},${songTitle}, ${videogameName}, ${userName}, ${songGenre}, ${subscriptionGroup}, ${usermailAddress}, ${accountId}, ${shopbyAge}, ${shopbyPrice}, ${ageRange}, ${interestgenreToys}, ${popularBooks}, ${textbookTitle}. ${bookFormat}, ${vehicleName}, ${autoPrice}, ${petType}, ${sellerName}</p>`);
